// Mapping des IDs de questions vers leurs textes
export const questionTextMap: Record<string, string> = {
  // Questions principales
  'main-1': 'Type de besoin',
  
  // Questions Argent
  'argent-1': 'Montant souhaité',
  'argent-2': 'Raison du prêt',
  'argent-3': 'Statut propriétaire',
  'argent-4': 'Durée de remboursement',
  'argent-5': 'Situation familiale',
  'argent-5b': 'Conjoint travaille',
  'argent-5c': 'Revenus du conjoint',
  'argent-6': 'Personnes à charge',
  'argent-7': 'Situation professionnelle',
  'argent-8': 'Ancienneté emploi',
  'argent-9': 'Revenus mensuels nets',
  'argent-11': 'Crédits en cours',
  'argent-12': 'Montant mensualités crédit',
  'argent-13': 'Incidents de paiement',
  
  // Questions Véhicule
  'vehicule-1': 'Type de véhicule',
  'vehicule-2': 'État du véhicule',
  'vehicule-3': 'Prix du véhicule',
  'vehicule-4': 'Apport personnel',
  'vehicule-5': 'Durée du crédit',
  'vehicule-6': 'Situation familiale',
  'vehicule-6b': 'Conjoint travaille',
  'vehicule-6c': 'Revenus du conjoint',
  'vehicule-7': 'Personnes à charge',
  'vehicule-8': 'Statut propriétaire',
  'vehicule-8b': 'Mensualité crédit immobilier',
  'vehicule-9': 'Situation professionnelle',
  'vehicule-10': 'Ancienneté emploi',
  'vehicule-10b': 'Fin de contrat',
  'vehicule-11': 'Revenus mensuels nets',
  'vehicule-11b': 'Revenus complémentaires',
  'vehicule-11c': 'Montant revenus complémentaires',
  'vehicule-12': 'Crédits en cours',
  'vehicule-13': 'Montant mensualités crédit',
  'vehicule-13b': 'Type de crédits',
  'vehicule-14': 'Incidents bancaires',
  'vehicule-15': 'Inscription FICP',
  'vehicule-16': 'Assurance emprunteur',
  
  // Questions Travaux
  'travaux-1': 'Type de travaux',
  'travaux-2': 'Statut propriétaire',
  'travaux-3': 'Surface du logement',
  'travaux-4': 'Montant des travaux',
  'travaux-5': 'Apport personnel',
  'travaux-6': 'Durée du crédit',
  'travaux-7': 'Situation familiale',
  'travaux-7b': 'Conjoint travaille',
  'travaux-7c': 'Revenus du conjoint',
  'travaux-8': 'Personnes à charge',
  'travaux-9': 'Situation professionnelle',
  'travaux-10': 'Ancienneté emploi',
  'travaux-11': 'Revenus mensuels nets',
  'travaux-11b': 'Revenus complémentaires',
  'travaux-11c': 'Montant revenus complémentaires',
  'travaux-12': 'Crédits en cours',
  'travaux-13': 'Montant mensualités crédit',
  'travaux-13b': 'Crédit immobilier',
  'travaux-14': 'Incidents bancaires',
  'travaux-15': 'Inscription FICP',
  
  // Questions Équipement
  'equipement-1': 'Type d\'équipement',
  'equipement-2': 'Montant de l\'équipement',
  'equipement-3': 'Apport personnel',
  'equipement-4': 'Durée du crédit',
  'equipement-5': 'Situation familiale',
  'equipement-5b': 'Conjoint travaille',
  'equipement-5c': 'Revenus du conjoint',
  'equipement-6': 'Personnes à charge',
  'equipement-7': 'Situation professionnelle',
  'equipement-8': 'Ancienneté emploi',
  'equipement-9': 'Revenus mensuels nets',
  'equipement-10': 'Crédits en cours',
  'equipement-11': 'Montant mensualités crédit',
  'equipement-12': 'Incidents de paiement',
  'equipement-13': 'Inscription FICP',
};

export function getQuestionLabel(questionId: string): string {
  return questionTextMap[questionId] || questionId;
}
